### ISSUE TITLE
Stopping and Starting CPE WAS Liberty is causing communication issues with DataSources

### ISSUE THREAD

**Issue by SKKOVVURI** [ibm-ecm/container-demo#17]
Hi,

 I tried to connect to the CPE container and restarted the defaultServer from within the container. Now I get a "Context Root Not found" error for both /FileNet/Engine and /acce. Here are the logs from p8_server_error_log.

com.filenet.api.exception.EngineRuntimeException: FNRCE0024E: E_FAILED_TO_GET_DATASOURCE: The server cannot get the data source FNGCDDS. Message was: [jcc][t4][2030][11211][4.26.14] A communication error occurred during operations on the connection's underlying socket, socket input stream,
or socket output stream.  Error location: Reply.fill() - insufficient data (-1).  Message: Insufficient data. ERRORCODE=-4499, SQLSTATE=08001 DSRA0010E: SQL State = 08001, Error Code = -4,499

...
..
com.filenet.api.exception.EngineRuntimeException: FNRCE0024E: E_FAILED_TO_GET_DATASOURCE: The server cannot get the data source FNOSDS. Message was: [jcc][t4][2030][11211][4.26.14] A communication error occurred during operations on the connection's underlying socket, socket input stream,
or socket output stream.  Error location: Reply.fill() - insufficient data (-1).  Message: Insufficient data. ERRORCODE=-4499, SQLSTATE=08001 DSRA0010E: SQL State = 08001, Error Code = -4,499
        at com.filenet.engine.context.ServerCallContext.getConnectionWithRetry(ServerCallContext.java:1334)
        at com.filenet.engine.context.ServerCallContext.getConnection(ServerCallContext.java:1271)
        at com.filenet.engine.context.ServerCallContext._getDBContext(ServerCallContext.java:1028)
        at com.filenet.engine.context.ServerCallContext._getDBContext(ServerCallContext.java:1160)
        at com.filenet.engine.context.ServerCallContext.getDBContext(ServerCallContext.java:823)
        at com.filenet.engine.metadatacache.ObjectStoreCache.buildNewObjectStoreCache(ObjectStoreCache.java:1869)
        at com.filenet.engine.metadatacache.ObjectStoreCache.getObjectStoreCache(ObjectStoreCache.java:1676)
        at com.filenet.engine.tasks.RootTask.loadObjectStores(RootTask.java:392)
        at com.filenet.engine.tasks.RootTask.unitOfWork(RootTask.java:223)
        at com.filenet.engine.tasks.ScheduledBackgroundTask.execute(ScheduledBackgroundTask.java:276)
        at com.filenet.engine.tasks.BackgroundTask.safeExecute(BackgroundTask.java:268)
        at com.filenet.engine.tasks.BackgroundTask$BackgroundTaskPrivilegedExceptionAction.run(BackgroundTask.java:1103)
        at com.filenet.engine.context.CallState._doAsSecurityContext(CallState.java:248)
        at com.filenet.engine.context.CallState.doAsSystem(CallState.java:298)
        at com.filenet.engine.tasks.BackgroundTask.run(BackgroundTask.java:200)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:820)
        at com.ibm.ws.concurrent.internal.ManagedThreadImpl.run(ManagedThreadImpl.java:94)
Caused by: java.sql.SQLNonTransientException: [jcc][t4][2030][11211][4.26.14] A communication error occurred during operations on the connection's underlying socket, socket input stream,
or socket output stream.  Error location: Reply.fill() - insufficient data (-1).  Message: Insufficient data. ERRORCODE=-4499, SQLSTATE=08001 DSRA0010E: SQL State = 08001, Error Code = -4,499

Restarting docker, stopping/starting db2/cpe did not help. Any ideas how to get things back to normal.

Thanks in advance,
Sai

**Comment by abrakhan** [comment]
Please attach the log files with the exception details.

-Abrar
