### ISSUE TITLE
Not possible to execute of asynchronous task in ICN Container

### ISSUE THREAD

**Issue by eugenone** [ibm-ecm/container-demo#18]
It is not possible to start an async task in ICN caused on following error: java.lang.ClassNotFoundException: commonj.work.Work.

 The ICN application folder WEB-INF/lib contains no commonj-twm.jar

`CIWEB Error: [P8Admin @ 192.168.56.1] com.ibm.ecm.mediator.PluginsInfoMediator.writeJSONResponse()
java.lang.NoClassDefFoundError: commonj.work.Work
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at com.ibm.ws.classloading.internal.AppClassLoader.definePackageAndClass(AppClassLoader.java:375)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:322)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:535)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:495)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:933)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:1225)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:730)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:1225)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
	at com.demo.ecm.icn.plugins.menu.DemoAsyncTaskType.getClassHandlerName(DemoAsyncTaskType.java:25)
	at com.ibm.ecm.util.PluginUtil.addPluginToJSONArray(PluginUtil.java:2162)
	at com.ibm.ecm.mediator.PluginsInfoMediator.toJSONObject(PluginsInfoMediator.java:85)
	at com.ibm.ecm.mediator.BaseMediator.toJSONString(BaseMediator.java:411)
	at com.ibm.ecm.mediator.BaseMediator.writeJSON(BaseMediator.java:534)
	at com.ibm.ecm.mediator.BaseMediator.writeJSON(BaseMediator.java:519)
	at com.ibm.ecm.mediator.BaseMediator.writeJSONResponse(BaseMediator.java:641)
	at com.ibm.ecm.struts.actions.BaseAction.writeJSONMediator(BaseAction.java:426)
	at com.ibm.ecm.struts.actions.GetPluginsInfoAction.executeBaseAction(GetPluginsInfoAction.java:54)
	at com.ibm.ecm.struts.actions.BaseActionHandlerImpl.executeAction(BaseActionHandlerImpl.java:466)
	at com.ibm.ecm.struts.actions.BaseAction.execute(BaseAction.java:76)
	at com.ibm.ecm.jaxrs.Actions.loadAndExecuteAction(Actions.java:719)
	at com.ibm.ecm.jaxrs.Actions.handleAction(Actions.java:111)
	at com.ibm.ecm.jaxrs.Actions.handlePostActions(Actions.java:148)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:205)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:111)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.ecm.filters.JAXRSFilter.doFilter(JAXRSFilter.java:42)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ecm.filters.ESAPIWafFilter.doFilter(ESAPIWafFilter.java:273)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ecm.filters.CORSFilter.doFilter(CORSFilter.java:104)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
Caused by: java.lang.ClassNotFoundException: commonj.work.Work
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:557)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:301)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:535)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:495)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
	... 96 more
`

**Comment by pdias-ibm** [comment]
@eugenone, could you please open a Case for this against Content Navigator.  This is more complex of an issue than this forum was intended.

**Comment by abrakhan** [comment]
The Task Manaer container is a separate container and is not deployed as part of this utility

-Abrar
